[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200
build_type = release
monitor_filters = time, colorize, esp32_exception_decoder
lib_deps = 
    SPI
    greiman/SdFat @ ^2.2.3
lib_extra_dirs = components
lib_ldf_mode = deep+

build_flags = 
    -I src
    -I .
    -D CORE_DEBUG_LEVEL=1