[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Serial monitor
monitor_speed = 115200

; Required libraries
lib_deps =
    adafruit/Adafruit BME680 Library
    adafruit/Adafruit Unified Sensor

; (Optional but recommended)
build_flags =
    -DCORE_DEBUG_LEVEL=0
