[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200
build_type = release
lib_deps = 
    jgromes/RadioLib @ ^6.4.0
    mikalhart/TinyGPSPlus @ ^1.0.3
    file://components/bme68x/BME68X_SensorAPI
    adafruit/Adafruit BMP3XX Library @ ^2.1.2
    adafruit/Adafruit Unified Sensor @ ^1.1.9
lib_extra_dirs = components
lib_ldf_mode = deep+

build_flags = 
    -I src
    -I .
    "-Icomponents/bme68x/BME68X_SensorAPI"
    -D CORE_DEBUG_LEVEL=3
    