[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit BME680 Library
  adafruit/Adafruit Unified Sensor
  rfetick/MPU6050_light

build_flags =
  -DTEST_MODE_ALL=1
  ;-DTEST_MODE_SERVO_UART=1
  ;-DTEST_MODE_LORA_UART=1
  ;-DTEST_MODE_SENSORS=1
  ;-DTEST_MODE_SD=1

// switch tests by uncommenting a line